# -*- coding: utf-8 -*-
"""Breast_cancer_Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sPFYAI23cZCYa9Nf_9L20Kdwt-DWhqH1

# Step 1  :Load and Explore the Dataset
"""

import pandas as pd
from google.colab import files
from sklearn.datasets import load_breast_cancer
df = load_breast_cancer()
df.target[[10, 50, 85]]
list(df.target_names)

df=pd.DataFrame(df.data,columns=df.feature_names)
df['target'] = load_breast_cancer().target
df.head()

df.describe()

df.shape

df.isnull().sum()

"""there are no null or missing values"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline
import warnings
warnings.filterwarnings("ignore")

df.head(2)

plt.scatter(x='mean radius',y='mean texture',data=df)
plt.xlabel('mean radius')
plt.ylabel('mean texture')
plt.show()

plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.hist(df['worst radius'], bins=10, edgecolor='black', color='green')
plt.title('Distribution of Worst Radius')
plt.xlabel('Worst Radius')
plt.ylabel('Frequency')

plt.subplot(1, 2, 2)
plt.hist(df['mean radius'], bins=10, edgecolor='black', color='red')
plt.title('Distribution of Mean Radius')
plt.xlabel('Mean Radius')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(
    data=df,
    x='mean perimeter',
    hue='target',
    bins=20,
    palette={0: 'red', 1: 'green'},
    alpha=0.5,
    edgecolor='black'
)

plt.title('Distribution of Mean Perimeter by Tumor Type', fontsize=14)
plt.xlabel('Mean Perimeter')
plt.ylabel('Frequency')
plt.legend(title='Tumor Type', labels=['Malignant (0)', 'Benign (1)'])
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(
    data=df,
    x='mean fractal dimension',
    hue='target',
    bins=20,
    palette={0: 'yellow', 1: 'purple'},
    alpha=0.5,
    edgecolor='black'
)

plt.title('Distribution of mean fractal by Tumor Type', fontsize=14)
plt.xlabel('mean fractal dimension')
plt.ylabel('Frequency')
plt.legend(title='Tumor Type', labels=['Malignant (0)', 'Benign (1)'])
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(
    data=df,
    x='worst radius',
    hue='target',
    bins=20,
    palette={0: 'orange', 1: 'grey'},
    alpha=0.5,
    edgecolor='black'
)

plt.title('Distribution of worst radius by Tumor Type', fontsize=14)
plt.xlabel('worst radius dimension')
plt.ylabel('Frequency')
plt.legend(title='Tumor Type', labels=['Malignant (0)', 'Benign (1)'])
plt.tight_layout()
plt.show()

"""# Step 2 :Data Split:"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

x1=df.drop('target',axis=1)
y1=df['target']
x_train,x_test,y_train,y_test=train_test_split(x1,y1,test_size=0.2,random_state=42)

"""# Step 3: Features Standardization:"""

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

"""Scaling helps the model learn faster because all features are on a similar scale. It prevents large-valued features from dominating and makes gradient-based optimization more stable.

# Step 4:  Train the Logistic Regression Model
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
lr=LogisticRegression()
lr.fit(x_train_scaled,y_train)
y_pred=lr.predict(x_test_scaled)
print("accuracy score",accuracy_score(y_test,y_pred))
print("confusion_matrix",confusion_matrix(y_test,y_pred))

from sklearn.metrics import classification_report
import pandas as pd

# Get the report as a dictionary
report_dict = classification_report(y_test, y_pred, output_dict=True)

# Convert to DataFrame
report_df = pd.DataFrame(report_dict).transpose()
print("classification report:")
print(report_df)

# coefficients:
print("Coefficients:", lr.coef_)
print("Intercept:", lr.intercept_)

coef_df = pd.DataFrame({
    'Feature': x_train.columns,
    'Coefficient': lr.coef_[0]
})
print(coef_df.sort_values(by='Coefficient', ascending=False))

"""# Step 5:Make predictions:"""

y_pred = lr.predict(x_test_scaled)
y_pred_proba = lr.predict_proba(x_test_scaled)

labels_10 = y_pred[:10]
probs_10 = y_pred_proba[:10]
df_pred = pd.DataFrame(probs_10, columns=[f'Prob_class_{c}' for c in range(probs_10.shape[1])])
df_pred['Predicted_Label'] = labels_10
print(df_pred)

"""# Step 6:Model Evaluation:"""

# Accuracy
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score

accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(y_test, y_pred)

recall = recall_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred)

roc_auc = roc_auc_score(y_test, y_pred_proba[:,1])

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("ROC AUC Score:", roc_auc)
#print(f"ROC-AUC: {roc_auc:.4f}") show only 4 digits rounded output

from sklearn.metrics import confusion_matrix, classification_report
y_pred = lr.predict(x_test_scaled)
confusion_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion_matrix)
report_dict = classification_report(y_test, y_pred, output_dict=True)
report_df = pd.DataFrame(report_dict).transpose()

print("Classification Report:")
print(report_df)

sns.heatmap(confusion_matrix, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.show()

report_metrics = report_df.iloc[:2, :3]

report_metrics.plot(kind='bar', figsize=(6,4))
plt.title("Classification Report Metrics per Class")
plt.ylabel("Score")
plt.ylim(0,1)
plt.xticks(rotation=0)
plt.show()

from sklearn.metrics import roc_curve, roc_auc_score

y_prob = lr.predict_proba(x_test_scaled)[:, 1]
fpr, tpr, thresholds = roc_curve(y_test, y_prob)


plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, color='blue', label=f'ROC curve (AUC = {roc_auc:.4f})')
plt.plot([0,1], [0,1], color='gray', linestyle='--', label='Random guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate (Recall)')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()

roc_auc = roc_auc_score(y_test, y_prob)
print("ROC AUC Score:", roc_auc)

"""1/for imbalanced data; accuracy could be misleading as it completely ignores or fails to detect the minority class even if accuracy is high(95%) it's catastrophic to not detect sick patients at such life/death cases as accuracy doesn't tell the whole story.

2/AUC=97% meaning:
If you randomly pick one benign and one malignant sample, the model has a 97% chance of assigning a higher probability to the benign sample than the malignant one.which means that the model is very good at ranking samples correctly.

# Step 8:Visualization:
"""

coef_df = pd.DataFrame({
    'Feature': x_train.columns,
    'Coefficient': lr.coef_[0]
})

# Take absolute values to see influence magnitude
coef_df['Abs_Coefficient'] = np.abs(coef_df['Coefficient'])

top_features = coef_df.sort_values(by='Abs_Coefficient', ascending=False).head(10)

plt.figure(figsize=(8,5))
plt.barh(top_features['Feature'][::-1], top_features['Coefficient'][::-1], color='skyblue')
plt.xlabel('Coefficient Value')
plt.title('Top 10 Most Influential Features')
plt.show()

y_prob = lr.predict_proba(x_test_scaled)[:, 1]
fpr, tpr, thresholds = roc_curve(y_test, y_prob)


plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, color='blue', label=f'ROC curve (AUC = {roc_auc:.4f})')
plt.plot([0,1], [0,1], color='gray', linestyle='--', label='Random guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate (Recall)')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()

from sklearn.metrics import precision_recall_curve, average_precision_score

precision, recall, _ = precision_recall_curve(y_test, y_prob)
avg_precision = average_precision_score(y_test, y_prob)

plt.figure(figsize=(6,5))
plt.plot(recall, precision, color='green', label=f'AP = {avg_precision:.4f}')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision–Recall Curve')
plt.legend(loc='lower left')
plt.show()

"""# Step 7: Threshold tuning:"""